### PR TITLE
topic/nuc

### PR DESCRIPTION
**Pull request by sguiriec**
@plbossart, @cc6565 please review CoE Audio HAL update for N release

### CODE REVIEW

**Comment by sguiriec** [comment]
@plbossart, @cc6565 please review the updated branch. Fix review comments and rename of AudioComms by AudioUtilities.

**Comment by plbossart** [comment]
looks good to me but I wonder if the name change is going to impact other plugins and create a mess?

**Comment by sguiriec** [comment]
Renaming will be done inside internal One Android tree in order to avoid the mess.

**Comment by plbossart** [comment]
Not sure I understand. When I look at vendor/intel/external/android_ia/ I see a ton of AudioCommsAssert and friends under hal and plugins
If I merge this patch then the HAL and plugins will break.
What am I missing?

**Comment by sguiriec** [comment]
Renaming has been done also on Audio HAL. Just need to cross check that update of the branch is push. Only impact is for Audio_route plugin that is not yet push

**Pull request merged**
